---
- hosts: all
  become: true 
  become_method: sudo 
  become_user: root 
  vars:
    document_root: /vagrant
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - webserver
    - database
